<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0.0000" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2022-09-13T20:31:11" tests="0" file="cypress/integration/Back-End/cy.login_com_sucesso" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="Testes automaticos da API consulta CEP" timestamp="2022-09-13T20:31:11" tests="1" time="0.0000" failures="1">
    <testcase name="Testes automaticos da API consulta CEP Consulta de um CEP válido" time="0.0000" classname="Consulta de um CEP válido">
      <failure message="Timed out retrying after 4000ms: expected undefined to equal &apos;false&apos;" type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 4000ms: expected undefined to equal 'false'
    at Context.eval (http://localhost:63119/__cypress/tests?p=cypress\integration\Back-End\cy.login_com_sucesso:110:53)]]></failure>
    </testcase>
  </testsuite>
</testsuites>